version: "3"

env:
    ### Global Variables
    
    ### Runtime Variables
    ARGOCD_PROJECTS: "01-BasicProject 02-ProjectRestrictions 03-ProjectRoles"
        
  ####### Create Resource Group and lauch VMs #######
tasks:
    ARGOCD:01-Create-projects:
      desc: Create a Projects for ArgoCD Applications
      cmds:
        - cmd: |
            for ARGOCD_APPLICATION in ${ARGOCD_APPLICATIONS}; do
              echo "✅ Creating ${ARGOCD_APPLICATION} application in ArgoCD"
              kubectl apply -f ./01-Applications/${ARGOCD_APPLICATION}.yaml
              echo "✅ Get the ${ARGOCD_APPLICATION} application with the following command:"
              kubectl get applications -n ${ARGOCD_APPLICATION}
              kubectl describe application -n argocd
            done