apiVersion: v1
kind: Secret
metadata:
  name: <cluster-name>-cluster-secret
  namespace: argocd # Namespace where ArgoCD is installed
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: <cluster-name> # A name to identify the cluster in ArgoCD
  server: <EKS-API-endpoint>
  config: |
    {
      "bearerToken": "<bearer-token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64-ca-data>"
      }
    }
