apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: emartapp-application
  annotations:
    argocd.argoproj.io/hook: PreSync # Ensure service is present before application sync
    argocd.argoproj.io/sync-wave: "-1" # Deploys very early
    argocd.argoproj.io/hook-delete-policy: HookFailed # define when the hook will be deleted
spec:
  selector:
    app: nginx

  ports:
  - port: 80
    targetPort: 80

  type: NodePort