apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  namespace: emartapp-application
  annotations:
    argocd.argoproj.io/hook: PreSync # Ensure service is present before application sync
    argocd.argoproj.io/sync-wave: "-1" # Deploys very early
    argocd.argoproj.io/hook-delete-policy: HookFailed # define when the hook will be deleted
data:
  MONGO_URI: "mongodb://admin:example@mongo-service:27017/epoc?authSource=admin"
  init-db.js: |
    db = db.getSiblingDB('epoc');
    db.createCollection("users");
    print("Database epoc initialized");