apiVersion: v1
kind: Service
metadata:
  name: javaapi-service
  namespace: emartapp-application
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  selector:
    app: javaapi-service

  ports:
  - port: 9000
    targetPort: 9000

  type: ClusterIP