apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: emartapp-application
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: darosa87/cloudchaps:1.0
        ports:
        - containerPort: 4200