apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: emartapp-application
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  selector:
    app: client

  ports:
  - port: 4200
    targetPort: 4200

  type: ClusterIP