apiVersion: v1
kind: Service
metadata:
  name: nodeapi-service
  namespace: emartapp-application
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  selector:
    app: nodeapi-service

  ports:
  - port: 5000
    targetPort: 5000

  type: ClusterIP