apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: helmk8s-project
  namespace: argocd
spec:
  description: helmk8s-project
  sourceRepos:
  - '*'

  destinations:
  - namespace: helm-config
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'