apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: sync-phases
  namespace: argocd
spec:
  destination:
    namespace: remote-cluster
    server: "https://7D3E2BB586258115FDAF52CCDA71FAF0.gr7.us-east-1.eks.amazonaws.com"
  project: default
  source: 
    path: 08-RemoteKubernetesClusters/02-Manifest/03-DeployManifest
    repoURL: "https://github.com/cloudchaps/ArgoCD_Examples.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true