version: "3"

env:
    ### Global Variables
    
    ### Runtime Variables
    ARGOCD_PROJECTS: "01-BasicProject 02-ProjectRestrictions 03-ProjectRoles"
    ARGOCD_APPLICATIONS: "01-Guestbook 02-Guestbook-Helm 03-Guestbook-Kustomize"
        
  ####### Create Resource Group and lauch VMs #######
tasks:
    ARGOCD:01-Create-projects:
      desc: Create a Projects for ArgoCD Applications
      cmds:
        - cmd: |
            kubectl create namespace k8s-plain-applications
            for ARGOCD_PROJECT in ${ARGOCD_PROJECTS}; do
              echo "✅ Creating ${ARGOCD_PROJECT} AppProject in ArgoCD"
              kubectl apply -f ./02-Manifest/01-BasicProjects/${ARGOCD_PROJECT}.yaml
              echo "✅ ${ARGOCD_PROJECT} AppProject created"
            done