apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kustomizek8s-project
  namespace: argocd
spec:
  description: project-with-role description
  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  - name: ci-role
    description: Sync privileges for project-with-role
    policies:
    - p, proj:kustomizek8s-project:ci-role, applications, sync, kustomizek8s-project/*, allow