apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: auto-pruning-demo
  namespace: argocd
spec: 
  destination:
    namespace: auto-pruning-demo
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: 02-AutomatedPruning
    repoURL: "https://github.com/cloudchaps/ArgoCD_Examples.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
      - CreateNamespace=true    